// --- BU BÖLÜMÜ src/lib/mockData.ts İÇİNE YAPIŞTIR ---

// 1. ANTRENMAN KARTLARI (Filtreleme için categoryFilter eklendi)
export const assignedWorkouts = [
  {
    id: "w1",
    title: "Arnold: Gün 1 & 4 (Göğüs & Sırt)",
    day: "Pazartesi",
    exercises: 7,
    duration: "75 dk",
    intensity: "Yüksek",
    coachNote: "Haftaya güçlü başla. Süpersetlerde nefesini ayarla. Odaklan.",
    categoryFilter: "Göğüs & Sırt", // Bu kategoriye sahip hareketleri çeker
  },
  {
    id: "w2",
    title: "Arnold: Gün 2 & 5 (Omuz & Kol)",
    day: "Salı",
    exercises: 7,
    duration: "60 dk",
    intensity: "Orta-Yüksek",
    coachNote: "Omuz başlarını hisset. Kollarda cheat yapma, nizami kaldır.",
    categoryFilter: "Omuz & Kol", // Bu kategoriye sahip hareketleri çeker
  },
  {
    id: "w3",
    title: "Arnold: Gün 3 & 6 (Bacak)",
    day: "Çarşamba",
    exercises: 6,
    duration: "80 dk",
    intensity: "Çok Yüksek",
    coachNote: "Squat'ta derin in. Bacaklar titreyene kadar durmak yok.",
    categoryFilter: "Bacak", // Bu kategoriye sahip hareketleri çeker
  },
];

// 2. DETAYLI EGZERSİZ LİSTESİ (Arnold Split - Temizlenmiş GIF Linkleri)
export const detailedExercises = [
  // --- DAY 1 & 4: GÖĞÜS & SIRT (CHEST & BACK) ---
  {
    id: "arnold_day1_1",
    name: "Flat Barbell Bench Press",
    category: "Göğüs & Sırt",
    targetReps: 12,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/8e/34/bb/8e34bb41d30ceb2f65aa7873a87a4371.gif",
    notes:
      "Piramit sistem uygula: 30, 12, 10, 8, 6 tekrar. Ağırlığı her sette artır. Barı göğsüne değdir, sektirme. O göğüsler patlayacak!",
  },
  {
    id: "arnold_day1_2",
    name: "Incline Barbell Bench Press",
    category: "Göğüs & Sırt",
    targetReps: 10,
    tempo: "3-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 8.5,
    videoUrl: "https://api.smartworkout.app/asset/image/20124d58-caef-b27e-8b5d-5d68fc46ca92",
    notes: "Üst göğüs boşsa tişört durmaz koçum. Açıyı her hafta değiştir (Düşük, Orta, Yüksek). İyice gerdir.",
  },
  {
    id: "arnold_day1_3",
    name: "Dumbbell Flyes",
    category: "Göğüs & Sırt",
    targetReps: 15,
    tempo: "3-1-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 0, // Superset
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/df/50/ac/df50ac81c3f3ba77e629e92c38b0ce8f.gif",
    notes: "Göğüs kafesini iyice aç, akciğerlerin hava dolsun. Kolları kırma.",
  },
  {
    id: "arnold_day1_4",
    name: "Dumbbell Pullover",
    category: "Göğüs & Sırt",
    targetReps: 15,
    tempo: "2-1-1-1",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 8,
    videoUrl: "https://i.pinimg.com/originals/79/b4/47/79b447fc9cf05bab3814c796f3837721.gif",
    notes: "Sırtını ve göğsünü aynı anda genişleten efsane hareket. Belini bükme.",
  },
  {
    id: "arnold_day1_5",
    name: "Wide Grip Chin Ups",
    category: "Göğüs & Sırt",
    targetReps: 10,
    tempo: "2-0-1-1",
    sets: 4,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 10,
    videoUrl: "https://api.smartworkout.app/asset/image/af3a0f69-0616-548d-a868-bf809b04bbb6",
    notes: "4 set tükenişe kadar! Çeneni bara vurmadan inmek yok. Kanatlarını hisset.",
  },
  {
    id: "arnold_day1_6",
    name: "Bent Over Barbell Row",
    category: "Göğüs & Sırt",
    targetReps: 12,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 60,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/a0/28/10/a0281013ad3889387260b853e96afabe.gif",
    notes: "Belini sakatlama, nizami dur. Piramit yapıyoruz: 30, 12, 10, 8, 6. Sırtın harita gibi olacak.",
  },
  {
    id: "arnold_day1_7",
    name: "Leg Raises",
    category: "Göğüs & Sırt", // Filtreleme kolaylığı için aynı gün kategorisine ekledik
    targetReps: 25,
    tempo: "1-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 30,
    rpe: 8,
    videoUrl: "https://i.pinimg.com/originals/70/82/ca/7082ca6f7a42e0098f04e6d7efb71472.gif",
    notes: "Karın kası mutfakta yapılır ama burada çelik gibi olur. 5 set 25 tekrar, acımak yok.",
  },

  // --- DAY 2 & 5: OMUZ & KOL (SHOULDERS & ARMS) ---
  {
    id: "arnold_day2_1",
    name: "Clean and Press",
    category: "Omuz & Kol",
    targetReps: 5,
    tempo: "X-0-X-0", // Patlayıcı
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 120,
    rpe: 9.5,
    videoUrl: "https://www.inspireusafoundation.org/file/2022/04/push-press.gif",
    notes: "Bu hareket adamı ayırır. Olimpik bir güç istiyorsan hakkını ver. 5 set 5 tekrar, ağır gir.",
  },
  {
    id: "arnold_day2_2",
    name: "Dumbbell Shoulder Press",
    category: "Omuz & Kol",
    targetReps: 10,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 0, // Superset
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/15/f1/bd/15f1bdf08aa6a5a5c65e8ef699a9d67b.gif",
    notes: "Front Raise ile süperset. Omuz başları yanacak, bırakmak yok!",
  },
  {
    id: "arnold_day2_3",
    name: "Full Frontal Raise",
    category: "Omuz & Kol",
    targetReps: 12,
    tempo: "2-0-1-1",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 8.5,
    videoUrl: "https://i.pinimg.com/originals/73/64/0b/73640b574358a88080b54b3aee57fbe1.gif",
    notes: "Sallanarak kaldırma, omuzu izole et. İyice tepeye kadar kaldır.",
  },
  {
    id: "arnold_day2_4",
    name: "Barbell Curl (1-10 Method)",
    category: "Omuz & Kol",
    targetReps: 10,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 60,
    rpe: 10,
    videoUrl: "https://i.pinimg.com/originals/a8/04/87/a80487b17f3acbbdcec864e582022b4a.gif",
    notes: "Cheating (hile) yok! Belden vurma. Haftaya 1-10 metodu (Ağırdan hafife durmadan) yapacağız, şimdiden alış.",
  },
  {
    id: "arnold_day2_5",
    name: "Close-Grip Bench Press",
    category: "Omuz & Kol",
    targetReps: 10,
    tempo: "3-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 60,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/2b/1f/e0/2b1fe00943bce0381f0cb6524ee323ba.gif",
    notes: "Arka kol (Triceps) için en baba hareket. Dirsekleri vücuda yapıştır.",
  },
  {
    id: "arnold_day2_6",
    name: "Barbell Skullcrushers",
    category: "Omuz & Kol",
    targetReps: 12,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 60,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/5e/0a/40/5e0a40361f52d1ede4264d1484217d4b.gif",
    notes: "Alnına indir, dirsekleri açma. Tricepsler kopana kadar devam.",
  },
  {
    id: "arnold_day2_7",
    name: "Wrist Curls",
    category: "Omuz & Kol",
    targetReps: 20,
    tempo: "1-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 30,
    rpe: 8,
    videoUrl: "https://i.pinimg.com/originals/7c/cd/14/7ccd14b0fd9239a93c6a73092a7e4ba2.gif",
    notes: "Bilekler önemli. Yanmayı hisset.",
  },

  // --- DAY 3 & 6: BACAK (LEGS) ---
  {
    id: "arnold_day3_1",
    name: "Barbell Squat",
    category: "Bacak",
    targetReps: 10,
    tempo: "3-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 120,
    rpe: 9.5,
    videoUrl: "https://i.pinimg.com/originals/d9/1c/3a/d91c3ab18a7673bc33d37caac1a669bd.gif",
    notes: "Kral hareket. Tam çök, yarım yapma. Bacakların titremeli. 8-12 tekrar arası kal.",
  },
  {
    id: "arnold_day3_2",
    name: "Stiff-Leg Deadlift",
    category: "Bacak",
    targetReps: 10,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/e8/0d/14/e80d14528c2588241f7439958a805809.gif",
    notes: "Arka bacak (Hamstring) ve kalça için. Dizleri çok kırma, esnemeyi hisset.",
  },
  {
    id: "arnold_day3_3",
    name: "Lunges",
    category: "Bacak",
    targetReps: 12,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 60,
    rpe: 8.5,
    videoUrl: "https://i.pinimg.com/originals/43/a4/f8/43a4f83040e08c9315a710235b34ad72.gif",
    notes: "Adımları uzun at. Dengeyi koru. Kalçayı sık.",
  },
  {
    id: "arnold_day3_4",
    name: "Leg Extension",
    category: "Bacak",
    targetReps: 15,
    tempo: "1-0-1-1",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 0, // Superset
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/cb/d6/72/cbd672eec0d13134ddd70697881aa97d.gif",
    notes: "Üst noktada bacakları sıkıştır, detaylar orada gizli.",
  },
  {
    id: "arnold_day3_5",
    name: "Leg Curl",
    category: "Bacak",
    targetReps: 15,
    tempo: "2-0-1-0",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 90,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/a1/a8/b7/a1a8b7369e4dbb3d999677f15b1606de.gif",
    notes: "Arka bacakları ihmal etme. Tam kapasite çek.",
  },
  {
    id: "arnold_day3_6",
    name: "Standing Calf Raises",
    category: "Bacak",
    targetReps: 20,
    tempo: "1-1-1-1",
    sets: 5,
    reps: 0,
    weight: 0,
    restDuration: 45,
    rpe: 9,
    videoUrl: "https://i.pinimg.com/originals/91/1f/b1/911fb167ad907dc16a293a59cb2d95db.gif",
    notes: "Kalf, Arnold'un zayıf noktasıydı, deli gibi çalıştı. Sen de öyle yapacaksın. Yanana kadar devam.",
  },
];
